//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class league
    {
        public league()
        {
            this.leagueparticipants = new HashSet<leagueparticipants>();
        }
    
        public int idLeague { get; set; }
        public string leagueName { get; set; }
        public int owner { get; set; }
        public int fromGameweek { get; set; }
    
        public virtual gameweek gameweek { get; set; }
        public virtual player player { get; set; }
        public virtual ICollection<leagueparticipants> leagueparticipants { get; set; }
    }
}
