//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playersteam
    {
        public playersteam()
        {
            this.player = new HashSet<player>();
            this.selectedsquad = new HashSet<selectedsquad>();
            this.transfer = new HashSet<transfer>();
        }
    
        public int idPlayersTeam { get; set; }
        public string playersTeamName { get; set; }
        public int gkPosition1 { get; set; }
        public int gkPosition2 { get; set; }
        public int defPosition1 { get; set; }
        public int defPosition2 { get; set; }
        public int defPosition3 { get; set; }
        public int defPosition4 { get; set; }
        public int defPosition5 { get; set; }
        public int midPosition1 { get; set; }
        public int midPosition2 { get; set; }
        public int midPosition3 { get; set; }
        public int midPosition4 { get; set; }
        public int midPosition5 { get; set; }
        public int fwPosition1 { get; set; }
        public int fwPosition2 { get; set; }
        public int fwPosition3 { get; set; }
    
        public virtual footballplayer footballplayer { get; set; }
        public virtual footballplayer footballplayer1 { get; set; }
        public virtual footballplayer footballplayer2 { get; set; }
        public virtual footballplayer footballplayer3 { get; set; }
        public virtual footballplayer footballplayer4 { get; set; }
        public virtual footballplayer footballplayer5 { get; set; }
        public virtual footballplayer footballplayer6 { get; set; }
        public virtual footballplayer footballplayer7 { get; set; }
        public virtual footballplayer footballplayer8 { get; set; }
        public virtual footballplayer footballplayer9 { get; set; }
        public virtual footballplayer footballplayer10 { get; set; }
        public virtual footballplayer footballplayer11 { get; set; }
        public virtual footballplayer footballplayer12 { get; set; }
        public virtual footballplayer footballplayer13 { get; set; }
        public virtual footballplayer footballplayer14 { get; set; }
        public virtual ICollection<player> player { get; set; }
        public virtual ICollection<selectedsquad> selectedsquad { get; set; }
        public virtual ICollection<transfer> transfer { get; set; }
    }
}
