//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public position()
        {
            this.footballplayer = new HashSet<footballplayer>();
        }
    
        public int idPosition { get; set; }
        public string positionName { get; set; }
        public string shortName { get; set; }
    
        public virtual ICollection<footballplayer> footballplayer { get; set; }
    }
}
