//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selectedsquad
    {
        public selectedsquad()
        {
            this.selectedsquadchecked = new HashSet<selectedsquadchecked>();
        }
    
        public int idSelectedSquad { get; set; }
        public int idPlayersTeam2 { get; set; }
        public bool gk1In { get; set; }
        public bool gk2In { get; set; }
        public bool def1In { get; set; }
        public bool def2In { get; set; }
        public bool def3In { get; set; }
        public bool def4In { get; set; }
        public bool def5In { get; set; }
        public bool mid1In { get; set; }
        public bool mid2In { get; set; }
        public bool mid3In { get; set; }
        public bool mid4In { get; set; }
        public bool mid5In { get; set; }
        public bool fw1In { get; set; }
        public bool fw2In { get; set; }
        public bool fw3In { get; set; }
    
        public virtual playersteam playersteam { get; set; }
        public virtual ICollection<selectedsquadchecked> selectedsquadchecked { get; set; }
    }
}
