//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selectedsquad
    {
        public selectedsquad()
        {
            this.selectedsquadchecked = new HashSet<selectedsquadchecked>();
        }
    
        public int idSelectedSquad { get; set; }
        public int idPlayersTeam2 { get; set; }
        public int gk1In { get; set; }
        public int gk2In { get; set; }
        public int def1In { get; set; }
        public int def2In { get; set; }
        public int def3In { get; set; }
        public int def4In { get; set; }
        public int def5In { get; set; }
        public int mid1In { get; set; }
        public int mid2In { get; set; }
        public int mid3In { get; set; }
        public int mid4In { get; set; }
        public int mid5In { get; set; }
        public int fw1In { get; set; }
        public int fw2In { get; set; }
        public int fw3In { get; set; }
    
        public virtual playersteam playersteam { get; set; }
        public virtual ICollection<selectedsquadchecked> selectedsquadchecked { get; set; }
    }
}
