//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selectedsquadchecked
    {
        public int idSelectedSquadChecked { get; set; }
        public int idSelectedSquad1 { get; set; }
        public int idGameWeek1 { get; set; }
    
        public virtual gameweek gameweek { get; set; }
        public virtual selectedsquad selectedsquad { get; set; }
    }
}
