//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public int idTransfer { get; set; }
        public int transferedPlayer { get; set; }
        public int transferedToTeam { get; set; }
    
        public virtual footballplayer footballplayer { get; set; }
        public virtual playersteam playersteam { get; set; }
    }
}
