//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usergroup
    {
        public usergroup()
        {
            this.user = new HashSet<user>();
        }
    
        public int idUserGroup { get; set; }
        public string groupName { get; set; }
    
        public virtual ICollection<user> user { get; set; }
    }
}
