//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public events()
        {
            this.matchevents = new HashSet<matchevents>();
        }
    
        public int idEvents { get; set; }
        public string eventName { get; set; }
    
        public virtual ICollection<matchevents> matchevents { get; set; }
    }
}
