//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class events
    {
        public events()
        {
            this.matchevents = new HashSet<matchevents>();
        }
        [Key]
        public int idEvents { get; set; }
        [Required(ErrorMessage = "Polje je potrebno popuniti!")]
        [StringLength(60, ErrorMessage = "Polje moze imati najmanje {2} karaktera i najvise {2} karaktera.", MinimumLength = 2)]
        public string eventName { get; set; }
    
        public virtual ICollection<matchevents> matchevents { get; set; }
    }
}
