//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class leagueparticipants
    {
        [Key]
        public int idLeagueParticipants { get; set; }
        public int participant { get; set; }
        public string status { get; set; }
        public int participatesIntoLeague { get; set; }
    
        public virtual league league { get; set; }
        public virtual user user { get; set; }
    }
}
