//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class league
    {
        public league()
        {
            this.leagueparticipants = new HashSet<leagueparticipants>();
        }
    
        [Key]
        public int idLeague { get; set; }
        [Required(ErrorMessage = "Polje je potrebno popuniti!")]
        [Display(Name = "Naziv lige")]
        public string leagueName { get; set; }
        [Required(ErrorMessage = "Polje je potrebno popuniti!")]
        [Display(Name = "Igrac")]
        public int owner { get; set; }
        [Required(ErrorMessage = "Polje je potrebno popuniti!")]
        [Display(Name = "Kolo")]
        public int fromGameweek { get; set; }
    
        public virtual gameweek gameweek { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<leagueparticipants> leagueparticipants { get; set; }
    }
}
