//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class matchevents
    {
        [Key]
        public int idMatchEvents { get; set; }
        public int idMatch1 { get; set; }
        public int idFootballPlayer1 { get; set; }
        public int minute { get; set; }
        public int idEvents1 { get; set; }
    
        public virtual events events { get; set; }
        public virtual footballplayer footballplayer { get; set; }
        public virtual match match { get; set; }
    }
}
