//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class playernews
    {
        [Key]
        public int idPlayerNews { get; set; }
        public string newsMessage { get; set; }
        public int idFootballPlayer1 { get; set; }
    
        public virtual footballplayer footballplayer { get; set; }
    }
}
