//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class squad
    {
        public squad()
        {
            this.selectedsquadchecked = new HashSet<selectedsquadchecked>();
            this.user = new HashSet<user>();
            this.squadplayer = new HashSet<squadplayer>();
        }
    
        public int idPlayersTeam { get; set; }
        public string playersTeamName { get; set; }
        public int GK_owned { get; set; }
        public int MF_owned { get; set; }
        public int DEF_owned { get; set; }
        public int FW_owned { get; set; }
    
        public virtual ICollection<selectedsquadchecked> selectedsquadchecked { get; set; }
        public virtual ICollection<user> user { get; set; }
        public virtual ICollection<squadplayer> squadplayer { get; set; }
    }
}
