//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETA.FantasyFootbalBHPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class squad
    {
        public int idPlayersTeam { get; set; }
        public string playersTeamName { get; set; }
        public int GK_owned { get; set; }
        public int MF_owned { get; set; }
        public int DEF_owned { get; set; }
        public int FW_owned { get; set; }
    }
}
